Text To Image更加详细的输出
cssxsh/stable-diffusion-helper pull request #2
Opened 2023-03-07 21:11 UTC by DRSalieri

1.新增TextToImageResponseInfo数据类，用于Json解析ImageResponse类的info成员（存储图片各种信息，如下图）

![image](https://user-images.githubusercontent.com/57832639/223553010-3cc99177-caf6-4c14-a4f4-bfa9b602fa85.png)

2.Text To Image 的输出更加详细（如下图）

![QQ截图20230308050339](https://user-images.githubusercontent.com/57832639/223552177-9b370b07-f109-4cbb-8545-0a7111f2bbf5.png)

主要修改了StableDiffusionListener的txt2img函数

2023-03-07 23:28 UTC, cssxsh requested changes

2023-03-07 23:28 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionHelper.kt
> +        StableDiffusionConfig.reload()                                      // 加载config
？

2023-03-07 23:28 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/diffusion/StableDiffusionTextToImageBuilder.kt
> +    public var height: Int = 512
为什么要改这里？

2023-03-07 23:28 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +        val seed1 = seed0.toLongOrNull() ?: (-1).toLong()
？

2023-03-07 23:48 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionHelper.kt
> +        StableDiffusionConfig.reload()                                      // 加载config
看代码的时候加的注释，可以忽略

2023-03-07 23:49 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/diffusion/StableDiffusionTextToImageBuilder.kt
> +    public var height: Int = 512
一般AI绘图默认生成512*512的图片，这里改了下默认值

2023-03-07 23:49 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionHelper.kt
> +        StableDiffusionConfig.reload()                                      // 加载config
> 看代码的时候加的注释，可以忽略

那你为什么要提交上来

2023-03-07 23:50 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +        val seed1 = seed0.toLongOrNull() ?: (-1).toLong()
当种子为-1时，webui会随机生成种子，所以不用引入随机数

2023-03-08 00:15 UTC, DRSalieri commented
已清除注释（本意是改给自己用，如果不需要这种输出，您直接close掉即可）

2023-03-08 01:15 UTC, cssxsh requested changes

2023-03-08 01:15 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/diffusion/StableDiffusionTextToImageBuilder.kt
> +    public var height: Int = 512
你应该新键一个 mirai console config 里面有 w/h 配置
然后在 StableDiffusionListener 里引用配置，而不是在这里修改

2023-03-08 01:15 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +        val seed1 = seed0.toLongOrNull() ?: (-1).toLong()
```suggestion
        val seed1 = seed0.toLongOrNull() ?: -1L
```

2023-03-08 01:15 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
>          launch {
以转发方式回复应该作为一个新功能添加
然后在配置文件加一个配置项，选择是否关闭或者开启

2023-03-08 10:44 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +internal object TextToImageConfig : ReadOnlyPluginConfig("TextToImage") {
用于配置Text To Image的config文件

2023-03-08 10:45 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +            if(TextToImageConfig.Detailed_output == true) {
Detailed_output在config文件内配置，为真时采用合并引用的方式输出，为否时只输出单张图片

2023-03-08 10:46 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    fun push(builder: StableDiffusionTextToImageBuilder)
用于将信息录入到Builder中，在Listener分析用户输入前被调用

2023-03-08 10:47 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionHelper.kt
> +        TextToImageConfig.reload()
加载新的Config文件

2023-03-08 10:48 UTC, DRSalieri reviewed
添加了Config文件用于配置TextToImage的参数，放在了新创建的包xyz.cssxsh.mirai.diffusion.config里

2023-03-08 10:50 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    fun push(builder: StableDiffusionTextToImageBuilder)
```suggestion
    fun push(builder: StableDiffusionTextToImageBuilder) {
```

统一代码风格

2023-03-08 10:51 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    val Detailed_output: Boolean by value(false)
```suggestion
    val detailedOutput: Boolean by value(false)
```

2023-03-08 10:52 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    @ValueName("Detailed Output")
```suggestion
    @ValueName("detailed_output")
```

2023-03-08 10:52 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    val n_iters: Int by value(1)
```suggestion
    val nIter: Int by value(1)
```

2023-03-08 10:53 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    val batch_size: Int by value(1)
```suggestion
    val batchSize: Int by value(1)
```

2023-03-08 10:53 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    val cfg_scale: Double by value(7.0)
```suggestion
    val cfgScale: Double by value(7.0)
```

2023-03-08 10:54 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    val sampler_name: String by value("Euler a")
```suggestion
    val samplerName: String by value("Euler a")
```

2023-03-08 11:02 UTC, DRSalieri reviewed
风格统一完成

2023-03-08 11:07 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/diffusion/StableDiffusionTextToImageBuilder.kt
> +    public var height: Int = 512
@DRSalieri 还原

2023-03-08 11:07 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/diffusion/data/TextToImageResponseInfo.kt
> +    val negative_prompt: String,
小驼峰

2023-03-08 11:16 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/config/TextToImageConfig.kt
> +    val width: Int by value(512)
默认值和 `StableDiffusionTextToImageBuilder` 一致，用户有需要再自己修改

2023-03-08 11:35 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +            if(TextToImageConfig.detailedOutput == true) {
```suggestion
            val message = if (TextToImageConfig.detailedOutput) {
```

2023-03-08 11:36 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +                val message = buildForwardMessage {
```suggestion
                buildForwardMessage {
```

2023-03-08 11:37 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +                subject.sendMessage(message)
```suggestion
```

2023-03-08 11:37 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +            }
```suggestion
            } else {
```

2023-03-08 11:38 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +                val message = response.images.mapIndexed { index, image ->
```suggestion
                response.images.mapIndexed { index, image ->
```

2023-03-08 11:41 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +                subject.sendMessage(message)
```suggestion
                }
                subject.sendMessage(message)
```

2023-03-08 11:42 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +            subject.sendMessage(At(sender))
`i2i` 的格式改到和上面的 `t2i` 一致
可以新增 `ImageToImageConfig`

2023-03-08 11:47 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +            } else {
我的意思整成
```
            } else {
                response.images.mapIndexed { index, image ->
                    val temp = out.resolve("${LocalDate.now()}/${seed1}.${response.hashCode().toHexString()}.${index}.png")
                    temp.parentFile.mkdirs()
                    temp.writeBytes(image.decodeBase64Bytes())

                    subject.uploadImage(temp)
                }.toMessageChain()
            }
            subject.sendMessage(message)
```

2023-03-08 12:06 UTC, cssxsh commented
考虑到只有反序列的需求 
`TextToImageResponseInfo` 这个类好像不是很必要
`info` 可以直接解析为 `JsonObject`, 然后需要什么再取什么

你觉得怎么样？

2023-03-08 12:08 UTC, DRSalieri commented
我之前也是这样想的，但是试了半天不会做（主要是string转jsonObject没找到合适的方法

2023-03-08 12:09 UTC, cssxsh commented
> 我之前也是这样想的，但是试了半天不会做（主要是string转jsonObject没找到合适的方法

```
Json.decodeFromString(JsonObject.serializer(), "...")
```

2023-03-08 13:23 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +                    val info = Json.decodeFromString(JsonObject.serializer(), response.info)
换成了Json对象，删除了TextToImageResponseInfo类

2023-03-08 13:24 UTC, DRSalieri commented on src/main/kotlin/xyz/cssxsh/mirai/diffusion/StableDiffusionListener.kt
> +            val message = when (TextToImageConfig.detailedOutput) {
使用`when(){}`来规整代码结构

2023-03-08 13:26 UTC, DRSalieri reviewed
添加了ImageToImage的config文件，并于listener中修改，效果如图
![image](https://user-images.githubusercontent.com/57832639/223724753-fe08f88c-89ec-4ae7-83dd-47f269742d98.png)
（格式化之后变动了一些import，应该不用管）

2023-03-08 15:39 UTC, cssxsh approved these changes

2023-03-08 15:40 UTC, merged